name: Build & Deploy news_bot

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # 1️⃣ 编译 Go 程序
  build:
    runs-on: ubuntu-latest
    container:
      image: hectorjiang/go-tdlib:latest  # 已经包含 TDLib
    steps:
      - uses: actions/checkout@v3
      - name: Download Go dependencies
        run: go mod tidy
      - name: Build news_bot
        run: go build -o news_bot main.go
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: news_bot-binary
          path: news_bot

  # 2️⃣ 部署到宿主机
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: news_bot-binary

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          script: |
            # 创建 TDLib 数据目录
            mkdir -p /opt/news_bot

            # 停止旧容器
            docker stop news_bot || true
            docker rm news_bot || true

            # 将二进制放到宿主机临时目录
            cp $GITHUB_WORKSPACE/news_bot /opt/news_bot/news_bot

            # 运行容器，挂载数据目录和二进制
            docker run -d \
              --name news_bot \
              -v /opt/news_bot:/app/tdlib-db \
              -v /opt/news_bot/news_bot:/app/news_bot \
              hectorjiang/go-tdlib:latest \
              /app/news_bot
