name: Deploy & Build news_bot

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取仓库代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ 上传代码到服务器
      - name: Sync code to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: 22
          source: "./"               # 仓库根目录
          target: "/opt/news_bot"    # 服务器目标目录

      # 3️⃣ 在服务器上编译
      - name: Compile on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: 22
          script: |
            cd /opt/news_bot

            # 下载依赖并编译
            go mod tidy
            go build -o news_bot main.go

            # 给二进制加执行权限
            chmod +x news_bot